### ISSUE TITLE
Scribble is not installing through NPM

### ISSUE THREAD

**Issue by dearzubi** [ConsenSys/scribble#136]
I have tried multiple times installing Scribble through NPM using the following command:

`sudo npm install -g eth-scribble`

Every time produces an error. Mostly the error is ERR_SOCKET_TIMEOUT or ECONNRESET.

Any guidance here? I am using node v16.13.1 and npm v8.1.2. Could this be an issue?

**Comment by blitz-1306** [comment]
Seems to be an internet connection issue and is probably not related to Scribble, as Scribble does not have any logic, that is using sockets or networking.

**Comment by dearzubi** [comment]
Internet connection seems fine and also tried on different internet connections as well. Same issue.

**Comment by dearzubi** [comment]
Update: It got resolved automatically.
