### ISSUE TITLE
Disallow `old()` expressions over maps and arrays

### ISSUE THREAD

**Issue by cd1m0** [ConsenSys/scribble#152]
Currently scribble allows `old()` expressions over maps and arrays. There are 3 problems with this:

1. `old()` expressions over maps will produce code that doesn't compile, as maps can't be copied and assigned.
2. `old()` expressions over arrays in memory are not compiled correctly, as the operation to "copy" the array in the old state is actually an aliasing assignment:

```
    _v.old0 = a; // where _v.old0 and a are both memory arrays aliases
```

3. Adding an array copy due to instrumentation significantly increases the number of paths that downstream tools like fuzzing and symbolic execution engines have to deal with.

Due to all of the above (especially 3) we've decided for now to disallow `old()` over dynamically sized containers like arrays and maps. 

To support the patterns that people may want to express with `old()` over arrays (e.g. `forall (uint i in old(a)) ...`) we are exploring adding more fine-grained annotations inside the function body

**Comment by cd1m0** [comment]
An interesting question here is if we should disallow `old()` over `strings` and `bytes` too? They are technically arrays from the point of view of the evm

**Comment by wuestholz** [comment]
@cd1m0 Yeah, I think we should disallow it for any collection (array, maps, strings, bytes, etc.) that would require copying the content.

**Comment by blitz-1306** [comment]
@cd1m0 Shouldn't we close this issue as resolved by https://github.com/ConsenSys/scribble/pull/153 ?

**Comment by cd1m0** [comment]
Yep!
