### ISSUE TITLE
GitCoin Bounty 💰  - Syntax Highlighting

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/scribble#16]
The most popular code understanding tool is syntax highlighting. Scribble is a specification language for Solidity smart contracts, where users write annotations in their smart contracts to formalise properties. Unfortunately, Scribble is a new language and there aren’t any highlighters written for it yet.

### ✍️  Description of Challenge
Scribble is a specification language for solidity smart contracts. This is a bounty for the implementation of syntax highlighting for Scribble annotations. 

### Requirements
1. Write a  grammar for Scribble annotations
	1. You can use either tree-sitter or TextMate
	2. The grammar should cover the features currently in Scribble. Including:
		1. if_succeeds
		2. invariant
		3. define
		4. let bindings
		5. old
		6. $result
		7. implication (==>)
	3. Add support for highlighting to the grammar (how depends on whether you’ll use tree-sitter or text-mate)
	4. If supported by the grammar tooling then there should be adequate tests.
2. Implement a VSCode plugin for Scribble
	1. This plugin should use the tree-sitter or text-mate highlighting to highlight scribble annotations
	2. Highlighting should use colours provided by the editor theme
3. Submit a PR for the add-on to [ConsenSys/scribble-highlighting](https://github.com/ConsenSys/scribble-highlighting)
    1. This PR should add both the required grammar and vscode plugin code
    

### ☑ Judging Criteria
* Test suite quality
* Implementation of CI/CD pipelines to automatically build, test and deploy newer versions of the tree-sitter grammar and VSCode package
* Maintainability, and available documentation
* You get bonus points if you also submit plugins for popular editors like vim 😁

#### 🔗  Useful Links
* [Scribble Documentation](https://docs.scribble.codes)
* [Tree-sitter｜Syntax Highlighting](https://tree-sitter.github.io/tree-sitter/syntax-highlighting)
* [Language Grammars — TextMate 1.x Manual](https://macromates.com/manual/en/language_grammars)
* [GitHub - JoranHonig/tree-sitter-solidity: Solidity grammar for tree sitter](https://github.com/JoranHonig/tree-sitter-solidity)
* [Syntax Highlight Guide | Visual Studio Code Extension API](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide)
* [Reference Scribble PEG.js grammar](https://github.com/ConsenSys/scribble/blob/develop/src/spec-lang/expr_grammar.pegjs)

### PS
If you're working on this bounty, then come hang out with us on [discord](https://discord.gg/E3YrVtG)! We'll be there to help you out in case you have any questions.

**Comment by cd1m0** [comment]
LGTM!
