### ISSUE TITLE
Impossible to use `forall` variable in `old` expression

### ISSUE THREAD

**Issue by NeverFearTomorrow** [ConsenSys/scribble#194]
I want to be able to `forall` over a discrete set of indices, and check the values of an array or map for said indices.
E.g.:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

contract Dummy2 {
  /// #if_updated
  ///   forall(uint i in 0...10)
  ///     let j := i * 2 in
  ///     things[j] > old(things[j]) ==> true;
  uint[20] things;
}
```
However, this gives the error
`Variable j is defined in the new context in (let j := (i * 2) in ((things[j] > old(things[j])) ==> true)) but used in an old() expression`

Per the docs, I changed it to:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

contract Dummy2 {
  /// #if_updated
  ///   forall(uint i in 0...10)
  ///     let j := old(i * 2) in
  ///     things[j] > old(things[j]) ==> true;
  uint[20] things;
}
```

However, this gives the error
`Forall variable i doesn't have old() in its range definition, but used in an old() expression`

So it seems impossible to get this to work.
It seems to me that it would be ok for a forall variable to have an `old` definition? It's timeless, so `old` should just be a noop, I guess?
While this example is very contrived, I wound up hitting this issue while trying to find a workaround for https://github.com/ConsenSys/scribble/issues/192 - without this workaround, I'm not sure if it will be possible to instrument my project with the current stable version of scribble.

**Comment by NeverFearTomorrow** [comment]
Worth noting - even if this were changed to say `forall(i in things)`, it would still produce the same error about `Forall variable i doesn't have old() in its range definition`. Is it just impossible to use `old` with `forall` variables? This seems unnecessarily restrictive, i feel like this is a vaild usage. I suppose the array or map could change, in which case the values to loop over would be different between old and new, but in that case, i'd think it would still work for a discrete, unrelated variable like `i in 0...10` as used in the original example

**Comment by cd1m0** [comment]
Appologies for the delay in responding. You are correct that its currently impossible to use the `forall` variable inside of an `old()` expression. The reason behind this is that implementing the instrumentation is very difficult. Consider for example:

```
/// #if_updated 
///       forall(uint i in a) 
///            i % 2 == 0 ==> old(a[i]) <= a[i];
uint[] a;
```

The entire `forall` loop is evaluated after the update. However for every even value of `i` we need to evaluate `old(a[i])` before the update, and store these somewhere. Doing this correctly involves some form of program slicing, and at best is something that we would only be able to for a limited set of cases. So for now we are not pursuing this.

An alternative solution we are considering would be to allow `old()` over complex data structures. Then you could implement the above annotation as follows:

```
/// #if_updated 
///       forall(uint i in a) 
///            i % 2 == 0 ==> old(a)[i] <= a[i];
uint[] a;
```
Note that in the above annotation there is no `i` inside `old` - instead we use `old()` to take a copy of the entire array before the update. The problem with this approach is that making copies of large data structures is very gas expensive, and my slow down fuzzing. So here our consideration is that we don't want to create a feature that is easy for users to shoot themselves in the foot with.

Finally, you might be able to achieve something close to what you want with an experimental feature we currently have -`if_assigned`. `if_assigned` differs from `if_updated` in that it allows you to check properties on updates to individual indices in an array. So you could express your original annotation as follows:

```
pragma solidity ^0.8.9;

contract Dummy2 {
  /// #if_assigned[i]
  ///    i % 2 == 0 ? ==> 
  ///        things[i] > old(things[i]) ==> true;
  uint[20] things;
}
```

Note that `if_assigned` will be checked on every assignment to `things[i]`, however unlike `if_updated` it won't be checked in the following cases:

1. `delete things`
2. `things.push(val)`
3. `things.pop(val)`
4. `things = someOtherArray`

In cases 1 and 3, there is no 'after' value of `things[i]`, In case 2 there is no `old()` value of `things[i]`. And in case 4, there are multiple updates happening, including potentially some with undefined new/old values. So please consider if `if_assigned` works for your use case.

Closing issue now, if you wish to continue the discussion, or there are any other questions please re-open
