### ISSUE TITLE
Scribble may break when interposing on overloaded functions

### ISSUE THREAD

**Issue by cd1m0** [ConsenSys/scribble#216]
Given this sample:

```
pragma solidity 0.8.19;

contract Target {
    function foo(uint x) public pure {}

    function foo(uint x, uint y) public payable {}
}

/// #invariant true;
contract Caller {

    function main(Target t) public {
        t.foo(1);

        t.foo(2, 3);
    }
}
```

Scribble throws an exception due to the following assert failing - https://github.com/ConsenSys/scribble/blob/develop/src/instrumenter/instrument.ts#L853

Basically the code for interposing on external callsites had an edge case where it didn't expect a function set type.

We can fix this by adding a new interface to solc-typed-ast (https://github.com/ConsenSys/solc-typed-ast/pull/189) that resolves overloaded functions so we don't have to deal with this edge case here.

**Comment by blitz-1306** [comment]
This is fixed by #217.
