### ISSUE TITLE
Interposed functions should be internal not private

### ISSUE THREAD

**Issue by cd1m0** [Consensys/scribble#257]
Given this sample:

```
contract Base {
   /// #if_succeeds true;
   function foo() internal returns (uint) {}
}

/// #invariant foo() == 1;
contract Child is Base {
}
```

The `foo` function in the base will be renamed to `__original_Base_foo` and made *private*. 
However in the instrumentation of `Child` we will try to use the interposed function (`__original_Base_foo`) which is no longer accessible in `Child` since its now private.

To fix this we should make interposed functions internal.

**Comment by blitz-1306** [comment]
This is addressed by #258. Closing.
