### ISSUE TITLE
Scribble fails on explicit call to inherited constructor.

### ISSUE THREAD

**Issue by ScottWe** [ConsenSys/scribble#63]
The following two examples are accepted by Scribble:
```solidity
contract A {
    int public a;
    constructor() {}
}

/// #invariant a >= 0;
contract B is A {
    constructor() {}
}
```
```solidity
contract A {
    int public a;
    constructor(int _a) { require(_a >= 0); a = _a; }
}

/// #invariant a > 0;
contract B is A(1) {
    constructor() {}
}
```
The following example yields `Error: Mismatch in length between [VariableDeclaration#6] of len 1 and [] of len 0`:
```
contract A {
    uint public a;
    constructor(uint _a) { require(_a >= 0); a = _a; }
}

/// #invariant a > 0;
contract B is A {
    constructor() A(1) {}
}
```
I am running the latest version of Scribble on npm using node version `10.24.1`.

**Comment by cd1m0** [comment]
Thank you for reporting this! Will take a look and root-cause tomorrow!

**Comment by cd1m0** [comment]
The problem arises when there is both an `InheritanceSpecifier` for a given contract, as well as a `ModifierInvocation`, and the arguments are specified in the `ModifierInvocation`. The logic in `getAssignments` (around here https://github.com/ConsenSys/scribble/blob/develop/src/instrumenter/state_vars.ts#L314) doesn't correctly account for this case, and it expects the `InheritanceSpecifier` to also have the right number of arguments.To fix this, we need to do a bit of pre-processing, to detect when there is a `ModifierInvocation` with arguments corresponding to a specific `InheritanceSpecifier` and ignore the `InheritanceSpecifier` in this case.
