### ISSUE TITLE
Support custom NatSpec tags

### ISSUE THREAD

**Issue by axic** [ConsenSys/scribble#67]
Since Solidity 0.8.2 (March 2021) custom NatSpec tags are supported (see the [docs](https://docs.soliditylang.org/en/latest/natspec-format.html?highlight=custom#tags) and [this discussion](https://github.com/ethereum/solidity/issues/8802) for context).

It would be nice for Scribble to support it, e.g.:
```
/// @custom:scribble if_succeeds {:msg "P0"} y == x + 1;
```

I understand that for supporting older language versions the current syntax should also be kept supported, but at least users' of newer versions can move on to custom tags, which means their NatSpec output will not have Scribble instructions in their user facing `@notice` tags.

**Comment by cd1m0** [comment]
Good call. Thank you for pointing out!
