### ISSUE TITLE
Support require-annotations to guide tools

### ISSUE THREAD

**Issue by wuestholz** [ConsenSys/scribble#93]
It could be useful to support require-annotation for guiding tools without changing the code itself. This could be very similar to the existing assert-annotations. Below is a more concrete example where some known tokens should be used as inputs:

```Solidity
contract C {
    function foo(address token) public {
      /// #require token == address(0x0) || token == address(0x1234) || token == address(0xabcd);
      ...
      token.transferFrom(...);
```

**Comment by cd1m0** [comment]
After additional discussion we decided to name the 2 new annotations `try` and `require`.

1. `try <predicate>` is transpiled as a vaciouos if:

```
if (<predicate>) {
  _v._scratch = 0x42;
}
```

The assignment inside the if generates a dead assignment to memory, that hopefully is not optimized away by the compiler.

2. `require <predicate>` is translated directly as a require:

```
require(predicate);
```

In the future we plan on allowing `try` to take a comma-separate list of predicates that are emitted as a sequence of ifs.
